kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  name: jenkins
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: thin
  volumeMode: Filesystem
