kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: pipeline-openshift-tasks
spec:
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  source:
    git:
      uri: "https://github.com/csfreitas/jenkins-pipelines-examples.git"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfiles/java-app.Jenkinsfile  
      env:
        - name: OPENSHIFT_PROJECT
          value: redhat-examples
        - name: OPENSHIFT_PROJECT_PROD
          value: redhat-examples-prod
        - name: APP_NAME
          value: openshift-tasks
