kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openshift-tasks-app
spec:
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  source:
    git:
      uri: "https://github.com/openshift/ruby-hello-world"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfiles/java-app.Jenkinsfile  
      env:
        - name: OPENSHIFT_PROJECT
          value: redhat-examples
  runPolicy: Serial
